### ISSUE TITLE
Question about the aspect detection task

### ISSUE THREAD

**Issue by xiulinyang** [UKPLab/controlled-argument-generation#14]
Hi, thank you very much for providing this interesting paper.

I have a question regarding the aspect detection task. In the paper, it says you fine-tuned the BERT model with the new aspect-annotated data (i.e., the output of the crowd sourcing), but why do you use ipa in the script to detect aspects for the downstream task? Did these two models (the fine-tuned BERT-large and the ipa.aspect) give the same results? If not, is it possible for us to have the BIO-tagged data and the checkpoint of the final BERT model? We hope to replicate your experiment in aspect detection.  Many thanks in advance for your time. :)

**Comment by v1nc3nt27** [comment]
Hi, thanks! Sorry for the late reply, I missed the notification.

What exactly do you mean with ipa? I used the BERT-base model (large was just too slow for so much data) to detect aspects for the downstream task. I don't have the model weights anymore, but it's pretty fast to train a BERT base version on the dataset (just use HF's `AutoModelForTokenClassification`). 

You can download the aspect detection dataset (and the the silver labeled CommonCrawl/Reddit data) from here: https://tudatalib.ulb.tu-darmstadt.de/handle/tudatalib/2329.

**Comment by xiulinyang** [comment]
> 

Hi, thank you very much for your reply!

Sorry for my typo - it should have been API. In the ```aspect_detection.py```, I noticed there is no BERT model used but just an api from Argumentsearch.com.  So I'm not very sure if you used the fine-tuned BERT model to detect the aspects for the downstream task. I apologise if I misunderstood it. :)

Also in the paper you said the BERT-large gave a better result in aspect detection (section 3.2), but why didn't you use the fine-tuned BERT-large for the downstream task? And may I know why you used the dataset with two different split methods? I totally understand the motivation of cross-topic data, that is, to see if the model could give proper result with new topics, but I didn't quite get the motivation for the in-topic data. I would really appreciate it if you could provide some of your opinions!

Sorry I asked too many questions. Many thanks in advance for your kind help. :)

**Comment by v1nc3nt27** [comment]
Ah, right, I forgot about that. After I trained the model I added this route in the argumentsearch API to make it easier for people who want to reproduce the results or just detect aspects in arguments. The model hosted there is the BERT base model mentioned in the paper. If you want to use it, you can just register at https://api.argumentsearch.com.

I didn't use BERT large because it's much slower and we had to classify millions of sentences. And the difference in F1 macro was "only" 1.2pp. With regard to the split, we just wanted to provide fixed data splits for both scenarios so future work would take these and make results comparable. There are a lot of datasets out there that come without splits and it's really hard to compare performance on them between works. There are valid scenarios where you'd only need performance on the topics you see at training.

**Comment by xiulinyang** [comment]
I see. It makes sense! Thank you very much. Everything is clear now. :)
